run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: mkdir
        run: | 
          mkdir output
          touch 1.img
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{secrets.CUSTOM_TOKEN}}
          name: ${{github.ref_name}}
          tag_name: ${{github.ref_name}}
          body_path: output/1.img
          discussion_category_name: Release
          files: 1.img
